### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by paulfloyd** [knatten/cpp-brain-teasers#1]
[ 38%] Linking CXX executable back-from-the-future
/home/pafloyd/tools/bin/ld: CMakeFiles/back-from-the-future.dir/back-from-the-future.cpp.o: in function `std::thread::_M_thread_deps_never_run()':
back-from-the-future.cpp:(.text._ZNSt6thread24_M_thread_deps_never_runEv[_ZNSt6thread24_M_thread_deps_never_runEv]+0x5): undefined reference to `pthread_create'
/home/pafloyd/tools/bin/ld: back-from-the-future.cpp:(.text._ZNSt6thread24_M_thread_deps_never_runEv[_ZNSt6thread24_M_thread_deps_never_runEv]+0xa): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/back-from-the-future.dir/build.make:97: back-from-the-future] Error 1
make[1]: *** [CMakeFiles/Makefile2:711: CMakeFiles/back-from-the-future.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

I'm using a nonstandard location for my GCC so I had to run cmake with

CC=gcc CXX=g++ LDFLAGS="-Wl,-rpath,${HOME}/tools/gcc/lib64 -pthread" cmake ..

In any case "-pthread" seems to be missing for a couple of the puzzles.

**Comment by knatten** [comment]
Are you sure that `-phtread` is needed here? This repo is [passing CI](https://github.com/knatten/cpp-brain-teasers/actions/runs/10953975939) out-of-the-box on Linux/gcc, Linux/clang, and Windows/MSVC. It's also building on Mac with AppleClang (not in CI).

**Comment by paulfloyd** [comment]
Yes I'm sure. Also on FreeBSD 14.1

```
[ 38%] Linking CXX executable back-from-the-future
ld: error: undefined symbol: pthread_create
>>> referenced by back-from-the-future.cpp
>>>               CMakeFiles/back-from-the-future.dir/back-from-the-future.cpp.o:(std::__1::__libcpp_thread_create[abi:se180100](pthread**, void* (*)(void*), void*))
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

With make VERBOSE-1
```
[ 37%] Linking CXX executable back-from-the-future
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/back-from-the-future.dir/link.txt --verbose=1
/usr/bin/c++ "CMakeFiles/back-from-the-future.dir/back-from-the-future.cpp.o" -o back-from-the-future
ld: error: undefined symbol: pthread_create
>>> referenced by back-from-the-future.cpp
>>>               CMakeFiles/back-from-the-future.dir/back-from-the-future.cpp.o:(std::__1::__libcpp_thread_create[abi:se180100](pthread**, void* (*)(void*), void*))
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Does ninja detect that -pthread is needed? You CI scripts use ninja but the book instructions on page xiv uses the default (Makefiles on Linux and FreeBSD).

**Comment by knatten** [comment]
I just added building with make to CI, and that works too. This problem might be specific to FreeBSD? Could you please try this branch and see if it fixes it? It doesn't make a difference on Linux, but hopefully fixes it for you. https://github.com/knatten/cpp-brain-teasers/tree/pthread

**Comment by paulfloyd** [comment]
It is not specific to FreeBSD. I also get the same problem on Rocky 8.10 with the system compiler (GCC 8.5).

The problem is that some code uses std::async which ultimately requires libpthread. I suspect that macOS and Windows don't have a separate libpthread so they never have this issue.

On your pthread branch you have the same problem with the std_atomic puzzle:

```
diff --git a/src/examples/std_atomic/CMakeLists.txt b/src/examples/std_atomic/CMakeLists.txt
index f8444dd..55a6c4f 100644
--- a/src/examples/std_atomic/CMakeLists.txt
+++ b/src/examples/std_atomic/CMakeLists.txt
@@ -2,5 +2,6 @@ add_executable(std_atomic std_atomic.cpp)
 if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang" OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
     if (UNIX AND NOT APPLE)
         target_link_libraries(std_atomic PRIVATE atomic)
+        target_link_libraries(std_atomic PRIVATE Threads::Threads)
     endif()
 endif ()
```

**Comment by knatten** [comment]
Right, I guess it's a change in a later GCC or that Ubuntu have some patches, then.

Will push a full fix to this repo shortly and talk to the publisher about updating the zip on their website. Thanks for reporting!

**Comment by paulfloyd** [comment]
This is not a recent thing. Unix compilers and link editors have worked this way for as long as I can remember - several decades.

I don't know CMake well and Ninja even less. Somthing in the CMake + Ninja flow must be adding the pthread flag.

**Comment by knatten** [comment]
> This is not a recent thing. Unix compilers and link editors have worked this way for as long as I can remember - several decades.

I meant that something has changed recently so one _doesn't_ need this flag anymore (not the other way around).

And that whatever this change is, it's not present in the distros you've been testing. (I also remember having to add this flag previously.)

> I don't know CMake well and Ninja even less. Somthing in the CMake + Ninja flow must be adding the pthread flag.

It's unlikely to be CMake+Ninja, since this works without the flag with both the Ninja and Unix Makefiles generators on Ubuntu 22.04 in CI (both with GCC and Clang). 

But anyway, the issue is fixed and I'm waiting for the publisher to update the zip file, so I'll stop the investigation here.

**Comment by knatten** [comment]
The new zip was published on Friday.
