### ISSUE TITLE
Any plans for chinese version

### ISSUE THREAD

**Issue by sweet2honey** [knatten/cpp-brain-teasers#4]
Hi Anders, I enjoyed the sample contents of your book and i think it deserves to be spread among more people. Would you consider a chinese translation of your book? I'd be more than happy to assist in any way I can to make that happen 😃

**Comment by knatten** [comment]
Thanks, I would love to see a Chinese translation! That's not up to me, though, but rather the publisher. You can try contacting The Pragmatic Programmers at proposals@pragprog.com.
